In [37]:
import pandas as pd
import numpy as np
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [8]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0], index =['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0], index =[2,5,3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [11]:
population_dict = {'California': 38332521,'Texas': 26448193,'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
population['California']

38332521

In [13]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [14]:
pd.Series ([2,4,6])

0    2
1    4
2    6
dtype: int64

In [15]:
pd.Series (5, index = [2,4,6])

2    5
4    5
6    5
dtype: int64

In [17]:
pd.Series ({2:'a',1:'b',3:'c'}, index = [3,2,9])

3      c
2      a
9    NaN
dtype: object

In [19]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}

In [20]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [21]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [22]:
states = pd.DataFrame({'population':population,'area':area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [23]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

In [25]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

In [26]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [29]:
pd.DataFrame(population,columns = ['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [34]:
data =[{'a': i,'b': 2 *i} for i in range (3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [35]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [36]:
pd.DataFrame([{'a':1, 'b':2},{'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [41]:
matrix = np.random.rand(3,2)
pd.DataFrame(matrix, columns=['foo', 'bar'], index = ['a','b','c'])

foo       bar
a  0.148873  0.457547
b  0.099437  0.363676
c  0.501575  0.748254

In [43]:
A = np.ones (3, dtype = [('A','i8'),('B','f8')])
A

array([(1, 1.), (1, 1.), (1, 1.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [44]:
pd.DataFrame(A)

A    B
0  1  1.0
1  1  1.0
2  1  1.0

In [45]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [46]:
ind[1]

3

In [47]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [49]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [51]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [52]:
indA & indB 

C:\Users\Admin\AppData\Local\Temp\ipykernel_5264\342904810.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB


Int64Index([3, 5, 7], dtype='int64')

In [53]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [54]:
indA | indB

C:\Users\Admin\AppData\Local\Temp\ipykernel_5264\3251124211.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [55]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [56]:
indA ^ indB

C:\Users\Admin\AppData\Local\Temp\ipykernel_5264\2832893868.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^ indB


Int64Index([1, 2, 9, 11], dtype='int64')

In [57]:
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

In [58]:
data = pd.Series([0.25,0.5,0.75,1.0], index =['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [59]:
data[1]

0.5

In [60]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [61]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [62]:
#Extend
data['e']=1.25

In [63]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [64]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [65]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [66]:
#masking
data[(data > 0.3) & (data <0.8)]

b    0.50
c    0.75
dtype: float64

In [67]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [68]:
data = pd.Series(['a','b','c'], index =[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [69]:
data[1]

'a'

In [70]:
data[1:3]

3    b
5    c
dtype: object

In [71]:
data.loc[1]

'a'

In [72]:
data.loc[1:3]

1    a
3    b
dtype: object

In [73]:
data.iloc[1]

'b'

In [74]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [76]:
pop = pd.Series({'California': 38332521,'Texas': 26448193,'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135})
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995})
data = pd.DataFrame({'area':area,'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [77]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [78]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [79]:
data.area is data['area']

True

In [80]:
data.pop is data['pop']

False

In [81]:
data.pop

<bound method DataFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [82]:
data['density']= data['pop']/data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [83]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [84]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [85]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [86]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [87]:
data.loc[:'Illinois',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [89]:
data.loc[data.density >100,['pop','density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [90]:
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763