In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import OneHotEncoder
data=np.asarray([['red'],['red'],['yellow'],['green'],['yellow']])
data

array([['red'],
       ['red'],
       ['yellow'],
       ['green'],
       ['yellow']], dtype='<U6')

In [3]:
type(data)

numpy.ndarray

In [4]:
encoder = OneHotEncoder(sparse = False)
onehot = encoder.fit_transform(data)
onehot

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [5]:
dm = ['red','red','yellow','green','yellow']
sr = np.array(dm)
sr=sr.reshape(5,1)
sr

array([['red'],
       ['red'],
       ['yellow'],
       ['green'],
       ['yellow']], dtype='<U6')

In [6]:
onehot = encoder.fit_transform(sr)
onehot

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [7]:
dm = ['red','red','yellow','green','yellow','blue']
sr = np.array(dm)
sr=sr.reshape(-1,1)
sr

array([['red'],
       ['red'],
       ['yellow'],
       ['green'],
       ['yellow'],
       ['blue']], dtype='<U6')

In [8]:
onehot = encoder.fit_transform(sr)
onehot

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [9]:
ser = pd.Series(dm)
ser

0       red
1       red
2    yellow
3     green
4    yellow
5      blue
dtype: object

In [10]:
ser.values

array(['red', 'red', 'yellow', 'green', 'yellow', 'blue'], dtype=object)

In [11]:
onehot = encoder.fit_transform(ser.values.reshape(-1,1))
onehot

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [12]:
df= ['red','red','yellow','green','yellow']
df = pd.DataFrame(df, index=[1,2,3,4,5],columns=['color'])
df

color
1     red
2     red
3  yellow
4   green
5  yellow

In [13]:
onehot = encoder.fit_transform(df['color'].values.reshape(-1,1))
onehot

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [14]:
#Mã hóa với pandas
pd.get_dummies(df)

color_green  color_red  color_yellow
1            0          1             0
2            0          1             0
3            0          0             1
4            1          0             0
5            0          0             1

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
lb = encoder.fit_transform(['red','red','yellow','green','yellow'])
lb

array([1, 1, 2, 0, 2], dtype=int64)

In [16]:
df

color
1     red
2     red
3  yellow
4   green
5  yellow

In [17]:
#Trả về dưới dạng array
lb= encoder.fit_transform(df['color'].values)
lb

array([1, 1, 2, 0, 2])

In [18]:
#Mã hóa với pandas
df['color'].dtype

dtype('O')

In [19]:
#Trả về dưới dạng frame
df['color'].astype('category').cat.codes

1    1
2    1
3    2
4    0
5    2
dtype: int8

In [20]:
a=df['color'].unique()
label = [i for i in range(len(a))]
_dict={a[i]: i for i in range(len(a))}
encoded = []
for i in df['color'].values:
    if i in _dict.keys():
        encoded.append(_dict[i])
encoded = pd.DataFrame(encoded)
encoded

0
0  0
1  0
2  1
3  2
4  1

In [21]:
a=df['color'].unique()
a=sorted(a)
label = [i for i in range(len(a))]
_dict={a[i]: i for i in range(len(a))}
encoded = []
for i in df['color'].values:
    if i in _dict.keys():
        encoded.append(_dict[i])
encoded = pd.DataFrame(encoded)
encoded

0
0  1
1  1
2  2
3  0
4  2

In [22]:
#Mã hóa với scikit-learn
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X= [['S',1],['M',2],['L',3]]
enc.fit_transform(X)

array([[2., 0.],
       [1., 1.],
       [0., 2.]])

In [23]:
df = pd.DataFrame({'Score':["Low","Low","Medium","Medium","High","Medium","High","Low"]})

In [24]:
scale_mapper = {"Low":1, "Medium":2,"High":3}
df['Scale']=df['Score'].replace(scale_mapper)
df

Score  Scale
0     Low      1
1     Low      1
2  Medium      2
3  Medium      2
4    High      3
5  Medium      2
6    High      3
7     Low      1

In [25]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
pd.cut(ages,bins)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [26]:
#Tự động chia nhóm
cut_data= pd.cut(ages,4)
cut_data

[(19.959, 30.25], (19.959, 30.25], (19.959, 30.25], (19.959, 30.25], (19.959, 30.25], ..., (30.25, 40.5], (50.75, 61.0], (40.5, 50.75], (40.5, 50.75], (30.25, 40.5]]
Length: 12
Categories (4, interval[float64, right]): [(19.959, 30.25] < (30.25, 40.5] < (40.5, 50.75] < (50.75, 61.0]]

In [27]:
cut_data= pd.qcut(ages,4)
cut_data

[(19.999, 22.75], (19.999, 22.75], (22.75, 29.0], (22.75, 29.0], (19.999, 22.75], ..., (29.0, 38.0], (38.0, 61.0], (38.0, 61.0], (38.0, 61.0], (29.0, 38.0]]
Length: 12
Categories (4, interval[float64, right]): [(19.999, 22.75] < (22.75, 29.0] < (29.0, 38.0] < (38.0, 61.0]]

In [28]:
genes=pd.read_csv(r'C:\Users\Admin\resources\gene_expression.csv',encoding = 'utf-8')
genes

G1        G2        G3        G4        G5        G6        G7  \
0   0.096999  0.227366  0.431403  0.350564  0.614166  0.037278  0.608806   
1   0.140357  0.116043  0.498218  0.286252  0.708196  0.037699  0.645638   
2   0.075864  0.215462  0.245413  0.263025  0.695526  0.057789  0.659812   
3   0.081394  0.193503  0.561137  0.133510  0.657569  0.053319  0.534083   
4   0.146972  0.019467  0.520126  0.200362  0.289476  0.146236  0.522055   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.136612  0.218060  0.410735  0.309124  0.623771  0.057232  0.758860   
96  0.181643  0.254944  0.502419  0.445739  0.604940  0.070491  0.521393   
97  0.086596  0.248284  0.417322  0.325038  0.642527  0.050735  0.553526   
98  0.154695  0.240120  0.572381  0.305699  0.612217  0.034965  0.692328   
99  0.148716  0.177830  0.536524  0.368034  0.599262  0.068033  0.719219   

          G8        G9       G10  ...       G91       G92       G93       G94  \
0   0.402018  0.024301  0.534258  ...  0.520794  0.348856  0.648020  0.460299   
1   0.447637  0.031831  0.444297  ...  0.609565  0.446938  0.655062  0.370700   
2   0.423609  0.005288  0.504874  ...  0.720783  0.311021  0.637153  0.415287   
3   0.415155  0.010994  0.408166  ...  0.670272  0.498790  0.549552  0.368304   
4   0.325684  0.009394  0.345423  ...  0.656710  0.488208  0.530460  0.392846   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.430003  0.002582  0.463476  ...  0.702393  0.469732  0.639036  0.406945   
96  0.399001  0.007459  0.497652  ...  0.678336  0.351175  0.651234  0.448695   
97  0.410098  0.044201  0.425274  ...  0.585763  0.481626  0.624413  0.323185   
98  0.418754  0.026105  0.553897  ...  0.551415  0.451893  0.601532  0.403350   
99  0.378219  0.009443  0.494733  ...  0.575103  0.464262  0.676459  0.479599   

         G95       G96       G97       G98       G99      G100  
0   0.422432  0.640388  0.238413  0.651695  0.536379  0.640927  
1   0.522416  0.594598  0.209250  0.590257  0.561454  0.548147  
2   0.405801  0.523387  0.278230  0.551977  0.588909  0.571148  
3   0.392148  0.643276  0.351833  0.681212  0.554729  0.498315  
4   0.365890  0.637134  0.240219  0.672030  0.520975  0.643914  
..       ...       ...       ...       ...       ...       ...  
95  0.464915  0.352919  0.368327  0.645155  0.459091  0.582123  
96  0.483983  0.610818  0.143644  0.564751  0.593970  0.798616  
97  0.538718  0.611075  0.256141  0.455464  0.264548  0.557122  
98  0.589157  0.586016  0.301276  0.662294  0.233315  0.577539  
99  0.472632  0.655524  0.267327  0.621181  0.500910  0.335473  

[100 rows x 100 columns]

In [29]:
genes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 100 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   G1      100 non-null    float64
 1   G2      100 non-null    float64
 2   G3      100 non-null    float64
 3   G4      100 non-null    float64
 4   G5      100 non-null    float64
 5   G6      100 non-null    float64
 6   G7      100 non-null    float64
 7   G8      100 non-null    float64
 8   G9      100 non-null    float64
 9   G10     100 non-null    float64
 10  G11     100 non-null    float64
 11  G12     100 non-null    float64
 12  G13     100 non-null    float64
 13  G14     100 non-null    float64
 14  G15     100 non-null    float64
 15  G16     100 non-null    float64
 16  G17     100 non-null    float64
 17  G18     100 non-null    float64
 18  G19     100 non-null    float64
 19  G20     100 non-null    float64
 20  G21     100 non-null    float64
 21  G22     100 non-null    float64
 22  G2

In [30]:
genes.describe()

G1          G2          G3          G4          G5          G6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.144753    0.238131    0.497430    0.348363    0.640078    0.044626   
std      0.044210    0.049367    0.063223    0.057892    0.070170    0.018359   
min      0.075864    0.019467    0.245413    0.133510    0.289476    0.012726   
25%      0.123418    0.214310    0.465339    0.309886    0.600458    0.032286   
50%      0.144430    0.236107    0.498217    0.345333    0.642243    0.042361   
75%      0.161552    0.263767    0.537322    0.378380    0.680568    0.053851   
max      0.430073    0.345238    0.660628    0.503123    0.785567    0.146236   

               G7          G8          G9         G10  ...         G91  \
count  100.000000  100.000000  100.000000  100.000000  ...  100.000000   
mean     0.632779    0.411069    0.018478    0.457512  ...    0.624771   
std      0.071070    0.060253    0.013653    0.064508  ...    0.069455   
min      0.423266    0.230732    0.001901    0.232383  ...    0.270370   
25%      0.587005    0.371785    0.009581    0.424590  ...    0.585241   
50%      0.624626    0.405469    0.016753    0.455546  ...    0.624864   
75%      0.673638    0.456319    0.022906    0.495078  ...    0.669081   
max      0.870245    0.551860    0.099483    0.640334  ...    0.786292   

              G92         G93         G94         G95         G96         G97  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.427851    0.633764    0.409029    0.452488    0.625421    0.261226   
std      0.062839    0.076273    0.066583    0.066099    0.062885    0.043232   
min      0.179199    0.304601    0.114740    0.191925    0.352919    0.143644   
25%      0.399608    0.590614    0.371815    0.413245    0.583688    0.232854   
50%      0.425329    0.629857    0.407328    0.456374    0.626779    0.260245   
75%      0.463704    0.676496    0.449498    0.493140    0.673498    0.285032   
max      0.555481    0.842580    0.548902    0.589157    0.734597    0.368327   

              G98         G99        G100  
count  100.000000  100.000000  100.000000  
mean     0.640700    0.550504    0.639582  
std      0.067306    0.076958    0.072268  
min      0.455464    0.233315    0.335473  
25%      0.596074    0.511474    0.596072  
50%      0.635023    0.553772    0.641620  
75%      0.674537    0.584104    0.682374  
max      0.835367    0.743485    0.826818  

[8 rows x 100 columns]

In [31]:
G1_cut=pd.cut(genes['G1'],3)
G1_cut

0     (0.0755, 0.194]
1     (0.0755, 0.194]
2     (0.0755, 0.194]
3     (0.0755, 0.194]
4     (0.0755, 0.194]
           ...       
95    (0.0755, 0.194]
96    (0.0755, 0.194]
97    (0.0755, 0.194]
98    (0.0755, 0.194]
99    (0.0755, 0.194]
Name: G1, Length: 100, dtype: category
Categories (3, interval[float64, right]): [(0.0755, 0.194] < (0.194, 0.312] < (0.312, 0.43]]

In [32]:
encoder = LabelEncoder()
lb = encoder.fit_transform(G1_cut.values)
lb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
kq= pd.DataFrame(i for i in range(0,100))
kq

0
0    0
1    1
2    2
3    3
4    4
..  ..
95  95
96  96
97  97
98  98
99  99

[100 rows x 1 columns]

In [34]:
for i in genes.columns:
    cut_ = pd.cut(genes[i],3)
    kq[i] = encoder.fit_transform(cut_.values)
kq

C:\Users\Admin\AppData\Local\Temp\ipykernel_19256\3247682930.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  kq[i] = encoder.fit_transform(cut_.values)


0  G1  G2  G3  G4  G5  G6  G7  G8  G9  ...  G91  G92  G93  G94  G95  G96  \
0    0   0   1   1   1   1   0   1   1   0  ...    1    1    1    2    1    2   
1    1   0   0   1   1   2   0   1   2   0  ...    1    2    1    1    2    1   
2    2   0   1   0   1   2   1   1   1   0  ...    2    1    1    2    1    1   
3    3   0   1   2   0   2   0   0   1   0  ...    2    2    1    1    1    2   
4    4   0   0   1   0   0   2   0   0   0  ...    2    2    1    1    1    2   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
95  95   0   1   1   1   2   1   2   1   0  ...    2    2    1    2    2    0   
96  96   0   2   1   2   1   1   0   1   0  ...    2    1    1    2    2    2   
97  97   0   2   1   1   2   0   0   1   1  ...    1    2    1    1    2    2   
98  98   0   2   2   1   1   0   1   1   0  ...    1    2    1    1    2    1   
99  99   0   1   2   1   1   1   1   1   0  ...    1    2    2    2    2    2   

    G97  G98  G99  G100  
0     1    1    1     1  
1     0    1    1     1  
2     1    0    2     1  
3     2    1    1     0  
4     1    1    1     1  
..  ...  ...  ...   ...  
95    2    1    1     1  
96    0    0    2     2  
97    1    0    0     1  
98    2    1    0     1  
99    1    1    1     0  

[100 rows x 101 columns]

In [35]:
#for i in genes.columns:
    #cut_ = pd.cut(genes[i],3)
    #lb = encoder.fit_transform(cut_.values)
    #genes[i]=lb

In [37]:
re_genes=pd.DataFrame()
for i in range(len(genes.columns)):
    ge=pd.cut(genes[f'G{i+1}'],3,labels=[0,1,2])
    re_genes[f'G{i+1}'] = ge
re_genes

G1 G2 G3 G4 G5 G6 G7 G8 G9 G10  ... G91 G92 G93 G94 G95 G96 G97 G98 G99  \
0   0  1  1  1  1  0  1  1  0   2  ...   1   1   1   2   1   2   1   1   1   
1   0  0  1  1  2  0  1  2  0   1  ...   1   2   1   1   2   1   0   1   1   
2   0  1  0  1  2  1  1  1  0   2  ...   2   1   1   2   1   1   1   0   2   
3   0  1  2  0  2  0  0  1  0   1  ...   2   2   1   1   1   2   2   1   1   
4   0  0  1  0  0  2  0  0  0   0  ...   2   2   1   1   1   2   1   1   1   
.. .. .. .. .. .. .. .. .. ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
95  0  1  1  1  2  1  2  1  0   1  ...   2   2   1   2   2   0   2   1   1   
96  0  2  1  2  1  1  0  1  0   1  ...   2   1   1   2   2   2   0   0   2   
97  0  2  1  1  2  0  0  1  1   1  ...   1   2   1   1   2   2   1   0   0   
98  0  2  2  1  1  0  1  1  0   2  ...   1   2   1   1   2   1   2   1   0   
99  0  1  2  1  1  1  1  1  0   1  ...   1   2   2   2   2   2   1   1   1   

   G100  
0     1  
1     1  
2     1  
3     0  
4     1  
..  ...  
95    1  
96    2  
97    1  
98    1  
99    0  

[100 rows x 100 columns]