In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r'C:\Users\Admin\resources\purchased.csv',encoding = 'utf-8')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [3]:
data.isna()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [4]:
#importing an aray of features
x=data.iloc[:,:-1].values
#importing an aray of dependent variable
y = data.iloc[:,-1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No ' 'Yes' 'No ' 'No ' 'Yes' 'Yes' 'No ' 'Yes' 'No ' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputa = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputa.fit(x[:,1:3])
x[:,1:3]=imputa.transform(x[:,1:3])

In [6]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
#Column Transformer cho phép onehot encoder 1 cột thay vì nguyên data frame
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#): cột thực hiện, remain: còn lại thì passthough
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [8]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y= encoder.fit_transform(y)

In [10]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [12]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x[:,3:]=sc.fit_transform(x[:,3:])

In [13]:
x

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [14]:
normalized_data= pd.DataFrame(x,columns=['0','1','2','Age','Salary'])
normalized_data

0    1    2       Age    Salary
0  1.0  0.0  0.0  0.758874  0.749473
1  0.0  0.0  1.0 -1.711504 -1.438178
2  0.0  1.0  0.0 -1.275555 -0.891265
3  0.0  0.0  1.0 -0.113024   -0.2532
4  0.0  1.0  0.0  0.177609       0.0
5  1.0  0.0  0.0 -0.548973 -0.526657
6  0.0  0.0  1.0       0.0  -1.07357
7  1.0  0.0  0.0   1.34014  1.387538
8  0.0  1.0  0.0  1.630773  1.752147
9  1.0  0.0  0.0  -0.25834  0.293712

In [16]:
purchased=pd.Series(y)
normalized_data['Purchased']=purchased
normalized_data

0    1    2       Age    Salary  Purchased
0  1.0  0.0  0.0  0.758874  0.749473          0
1  0.0  0.0  1.0 -1.711504 -1.438178          1
2  0.0  1.0  0.0 -1.275555 -0.891265          0
3  0.0  0.0  1.0 -0.113024   -0.2532          0
4  0.0  1.0  0.0  0.177609       0.0          1
5  1.0  0.0  0.0 -0.548973 -0.526657          1
6  0.0  0.0  1.0       0.0  -1.07357          0
7  1.0  0.0  0.0   1.34014  1.387538          1
8  0.0  1.0  0.0  1.630773  1.752147          0
9  1.0  0.0  0.0  -0.25834  0.293712          1

In [18]:
re_data=data.dropna()
re_data

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [19]:
re_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    8 non-null      object 
 1   Age        8 non-null      float64
 2   Salary     8 non-null      float64
 3   Purchased  8 non-null      object 
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes


In [20]:
#Dữ liệu ngoại lai
from scipy import stats
z=stats.zscore(re_data['Age'])
noisy=np.where((z>3)|(z<-3))
noisy

(array([], dtype=int64),)

In [21]:
z=stats.zscore(re_data['Salary'])
noisy=np.where((z>3)|(z<-3))
noisy

(array([], dtype=int64),)

In [22]:
from sklearn.preprocessing import StandardScaler
s_scaler = StandardScaler()
da=pd.DataFrame()
da['Age']=re_data['Age']
da['Salary']=re_data['Salary']
da
df_s = s_scaler.fit_transform(da)
df_s=pd.DataFrame(df_s,columns=['Age','Salary'])
#re_data['Age']=df_s['Age']
#re_data['Salary']=df_s['Salary']

In [24]:
#Chuẩn hóa dữ liệu
from sklearn.preprocessing import StandardScaler
s_scaler = StandardScaler()
sr=np.array(re_data['Age'])
sr=sr.reshape(-1,1)
df_s = s_scaler.fit_transform(sr)
df_s=pd.DataFrame(df_s,columns=['Age'])
print(df_s)

        Age
0  0.699858
1 -1.513647
2 -1.123028
3 -0.081379
4 -0.471997
5  1.220683
6  1.481095
7 -0.211585


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
re_data['Purchased']= encoder.fit_transform(re_data['Purchased'].values)
re_data['Country']= encoder.fit_transform(re_data['Country'].values)
re_data